server {
    listen 80;
    server_name x.nexus-x.site;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name x.nexus-x.site;

    ssl_certificate /etc/letsencrypt/live/x.nexus-x.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/x.nexus-x.site/privkey.pem;

    client_max_body_size 50M;
    keepalive_timeout 75;
    keepalive_requests 1000;
    
    # Gzip settings for maximum performance
    gzip on;
    gzip_static on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_min_length 256;
    gzip_types 
        text/plain 
        text/css 
        application/json 
        application/javascript 
        application/x-javascript 
        text/xml 
        application/xml 
        application/xml+rss 
        text/javascript 
        application/vnd.ms-fontobject 
        application/x-font-ttf 
        font/opentype 
        image/svg+xml 
        image/x-icon;

    # Performance headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "no-referrer-when-downgrade";


    # Use Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    # API Proxy
    location /api/ {
        proxy_pass http://nexus_api:3005/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Frontend Proxy
    location / {
        proxy_pass http://nexus_frontend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
